src/Entity/Property.php
<?php

namespace App\Entity;

use App\Repository\PropertyRepository;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=PropertyRepository::class)
 * @UniqueEntity("title")
 * @Vich\Uploadable
 */
class Property
{

    const HEAT = [
        0 => "Electric",
        1 => "Fioul"
    ];

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;


    /**
     * @var string|null
     * @ORM\Column(type="string", length=255)
    */
    private $fileName;

    /**
     * @var File|null
     * @Vich\UploadableField(mapping="property_image", fileNameProperty="fileName", size="imageSize")
     * @Assert\Image(mimeTypes="image/jpeg")
    */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=5, max=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @Assert\NotBlank
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min=10, max=500)
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adress;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex("/^[0-9]{5}$/")
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $sold = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\ManyToMany(targetEntity=Option::class, inversedBy="properties")
     */
    private $options;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\Column(type="integer", nullable=true)
     *
     * @var int|null
     */
    private $imageSize;

    public function __construct()
    {
        $this->created_at = new DateTime();
        $this->options = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }


    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    /**Slug usin Slugify library */
    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->title);
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function getFormatedPrice() :string
    {
        return number_format($this->price, 0, '', ' ');
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function getHeatType(): string
    {
        return self::HEAT[$this->heat];
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection|Option[]
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Option $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
            $option->addProperty($this);
        }

        return $this;
    }

    public function removeOption(Option $option): self
    {
        if ($this->options->contains($option)) {
            $this->options->removeElement($option);
            $option->removeProperty($this);
        }

        return $this;
    }

    public function setImageFile(?File $imageFile): Property
    {
        $this->imageFile = $imageFile;

        if($this->imageFile instanceof UploadedFile)
        {
            $this->updated_at = new \DateTime('now');
        }

        return $this;
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setFileName(?string $fileName): Property
    {
        $this->fileName = $fileName;
        return $this;
    }

    public function getFileName(): ?string
    {
        return $this->fileName;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function setImageSize(?int $imageSize): void
    {
        $this->imageSize = $imageSize;
    }

    public function getImageSize(): ?int
    {
        return $this->imageSize;
    }
}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Property;
use App\Entity\Option;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('surface')
            ->add('rooms')
            ->add('bedrooms')
            ->add('floor')
            ->add('price')
            ->add('heat', ChoiceType::class, [
                'choices' => $this->getChoices()
            ])
            ->add('options', EntityType::class, [
                'class' => Option::class,
                'required' => false,
                'choice_label' => 'name',
                'multiple' => true
            ])
            ->add('imageFile', FileType::class, [
                'required' => false
            ])
            ->add('city')
            ->add('adress', null, [
                'label' => 'Address'
            ])
            ->add('postal_code', null, [
                'label' => 'Postal'
            ])
            ->add('sold')
            //->add('created_at')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
        ]);
    }
    
    /**Faire sortir la valeur en premier a la place de la clé dans le array de Property::Heat */
    private function getChoices()
    {
        $choices = Property::HEAT;

        $outpout = [];

        foreach($choices as $k => $value) {
            $outpout[$value] = $k;
        }
        return $outpout;
    }
}

src/Controller/PropertyController.php
<?php

namespace App\Controller;

use App\Entity\Contact;
use App\Entity\Property;
use App\Entity\PropertySearch;
use App\Form\PropertySearchType;
use App\Form\ContactType;
use App\Notification\ContactNotification;
use App\Repository\PropertyRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PropertyController extends AbstractController
{
    /**
     * ETAPE 0 Créer un objet dans la DB via sont Entity 
     * $property = new Property();
        *$property->setTitle('First House')
        *    ->setPrice(300000)
        *    ->setRooms(5)
        *    ->setBedrooms(3)
        *    ->setDescription('B T H')
        *    ->setSurface(60)
        *    ->setFloor(2)
        *    ->setHeat(1)
        *    ->setCity('NEW YORK')
        *    ->setAdress('Greenfiel Park')
        *    ->setPostalCode(10000);

        *    $em = $this->getDoctrine()->getManager();
        *    $em->persist($property);
        *    $em->flush();
    */

    /**ETAPE 1 Injection de Dépendance des données via PropertyRepository dans le constructeur*/

    private $propertyRepository;
    private $em;

    public function __construct(PropertyRepository $propertyRepository, EntityManagerInterface $em)
    {
       $this->propertyRepository = $propertyRepository;
       $this->em = $em;
    }
        

    /**ETAPE 2 RECUPERER LES DONNÉES DANS LA DB VIA L'OBJET REPOSITORY INJECTER DANS LE CONSTRUCT OU METHODE SELON PERTINANCE */

    /**
     * @Route("/properties", name="property.index")
     */
    public function index(PaginatorInterface $paginator, Request $request) :Response
    {
        $search = new PropertySearch();
        $form = $this->createForm(PropertySearchType::class, $search);
        $form->handleRequest($request);
        /*Dans ce cas ci je récupère les maison non vendu en me servant de findAllUnsoldHomeQuery() dans PropertyRepository*/
        $properties = $paginator->paginate($this->propertyRepository->findAllUnsoldHomeQuery($search),
        $request->query->getInt('page', 1), 12);
        

        /*Détécte le changement d'état si je vend la maison par exemple*/
        $this->em->flush();

        return $this->render('property/index.html.twig', [
            'current_menu' => 'properties',
            'properties' => $properties,
            'form' => $form->createView(),
        ]);
    }

    /**ETAPE 3 Montrer le bien Selectioné avec slug et id */
    /**
     * @Route("/properties/{slug}-{id}", name="property.show", requirements={"slug": "[a-z0-9\-]*"})
     */
    public function show(Property $property, string $slug, Request $request, ContactNotification $notification): Response //$property = $this->propertyRepository->find($id); Ce fait dans la méhode show grace a l'Injection
    {   
        if($property->getSlug() !== $slug){
            return $this->redirectToRoute('property.show', [
                'id' => $property->getId(),
                'slug' => $property->getSlug()
            ], 301);
        }

        $contact = new Contact();
        $contact->setProperty($property);

        $form = $this->createForm(ContactType::class, $contact);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $notification->notify($contact);
            $this->addFlash('success', 'Your email has been send successfuly');
            
            return $this->redirectToRoute('property.show', [
                'id' => $property->getId(),
                'slug' => $property->getSlug()
            ]);
        }


        return $this->render('property/show.html.twig', [
            'property' => $property,
            'current_menu' => 'properties',
            'form' => $form->createView()
        ]);
    }
}

templates/property/_properties.html.twig
<div class="card mb-4">
    {% if property.filename %}
        <img src="{{ vich_uploader_asset(property, 'imageFile') }}" alt="card-img-top" style="width: 100%; height:auto">
    {% else %}
        <img src="{{ '/images/properties/empty.jpg' }}" alt="card-img-top" style="width: 100%; height:auto">
    {% endif %}

    <!--     <img src=" vich_uploader_asset(property, 'imageFile') | imagine_filter('thumb') }}" alt="card-img-top" style="width: 100%; height:auto"> -->
    <div class="card-body">
        <h5 class="car-title">
            <a href="{{ path('property.show', {id: property.id, slug: property.slug}) }}">{{ property.title }}</a>
        </h5>
        <p class="card-text">{{ property.description | nl2br }} </p>
        <p class="card-text">{{ property.surface}} m2 - {{ property.city }} ({{ property.postalCode }})</p>
        <p class="text-primary" style="font-size:2rem; font-weight:bold;">{{ property.formatedPrice }} $</p>
    </div>
</div>
            

templates/property/index.html.twig
{% extends 'base.html.twig' %}

{% block title 'All Properties !'%}

{% block body %}
<div class="jumbotron">
    <div class="container">
        {{ form_start(form) }}
            <div class="form-row align-items-end">
                <div class="col">
                    {{ form_row(form.minSurface) }}
                </div>
                 <div class="col">
                    {{ form_row(form.maxPrice) }}
                </div>
                <div class="col">
                    {{ form_row(form.options) }}
                </div>
                 <div class="col">
                    <div class="form-group">
                        <button type="submit" class="btn btn-secondary">Search</button>
                    </div>
                </div>
            </div>
        {{ form_end(form) }}
    </div>
</div>
<div class="container">
    <h1>Our Homes</h1>
    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Similique at error, accusantium sequi libero illo obcaecati molestias vel cum, recusandae hic totam ullam velit ex soluta a nihil omnis et?</p>
</div>
<div class="container mt-4">
    <h2>Homes for sales !</h2>
        <div class="row">
            {% for property in properties %}
            <div class="col-md-4">
                {% include 'property/_properties.html.twig' %}
            </div>
        {% endfor %}
        </div>
        <div class="pagination">
            {{ knp_pagination_render(properties) }}
        </div>
 </div>
 
{% endblock %}

templates/property/show.html.twig
{% extends 'base.html.twig' %}

{% block title property.title %}

{% block body %}
<div class="jumbotron">
    <div class="container">

     {% for message in app.flashes('success') %}
        <div class="alert alert-success">
            {{ message }}
        </div>
    {% endfor %}

      <div class="row">
        <div class="col-md-8">
        {% if property.filename %}
            <img src="{{ vich_uploader_asset(property, 'imageFile') }}" alt="card-img-top" style="width: 100%; height:auto">
        {% else %}
            <img src="{{ '/images/properties/empty.jpg' }}" alt="card-img-top" style="width: 100%; height:auto">
        {% endif %}
        </div>
        <div class="cold-md-4">
             <h1>{{ property.title }}</h1>
              <h2>{{ property.rooms }} rooms - {{ property.surface }} m2</h2>
                <div class="text-primary">{{ property.formatedPrice }} $</div>
                <a href="#" class="btn btn-primary" id="contactButton" {% if form.vars.submitted %} style="display: none;" {% endif %}>Contact Us</a>
                <div id="contactForm" class="mt-4" {% if not form.vars.submitted %} style="display: none;" {% endif %}>
                    {{ form_start(form) }}
                        <div class="row">
                            <div class="col">{{ form_row(form.firstname) }}</div>
                            <div class="col">{{ form_row(form.lastname) }}</div>
                        </div>
                        <div class="row">
                            <div class="col">{{ form_row(form.phone) }}</div>
                            <div class="col">{{ form_row(form.email) }}</div>
                        </div>
                        {{ form_rest(form) }}
                        <div class="form-group">
                            <button class="btn btn-primary">Send Message</button>
                        </div>
                    {{ form_end(form) }}
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container mt-4">
  

    <nav class="nav nav-tabs" id="tab"></nav>

    <p>
        {{ property.description | nl2br }}
    </p>

    <div class="row">
        <div class="col-md-8">
            <h2>More Infos</h2>
            <table class="table table-striped">
                <tr>
                    <td>Size</td>
                    <td>{{ property.surface }} m2</td>
                </tr>
                <tr>
                    <td>Rooms</td>
                    <td>{{ property.rooms }}</td>
                </tr>
                <tr>
                    <td>Bedrooms</td>
                    <td>{{ property.bedrooms }}</td>
                </tr>
                <tr>
                    <td>Floor</td>
                    <td>{{ property.floor }}</td>
                </tr>
                <tr>
                    <td>Heat type</td>
                    <td>{{ property.heatType }}</td>
                </tr>
            </table>
        </div>
        <div class="col-md-4">
            <h2>Specifiction</h2>

            <ul class="list-group">
               {% for option in property.options %}
                <li class="list-group-item">{{ option.name }}</li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}